// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_CfJf6E2KZ13cbs2VJCxpaBwy2fTG4lc',
    appId: '1:821231678050:android:3ed22ac41da79f72fad73b',
    messagingSenderId: '821231678050',
    projectId: 'carpool-app-5abb3',
    storageBucket: 'carpool-app-5abb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CfJf6E2KZ13cbs2VJCxpaBwy2fTG4lc',
    appId: '1:821231678050:ios:placeholder123',
    messagingSenderId: '821231678050',
    projectId: 'carpool-app-5abb3',
    iosBundleId: 'com.carpool.carpoolApp',
    storageBucket: 'carpool-app-5abb3.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_CfJf6E2KZ13cbs2VJCxpaBwy2fTG4lc',
    appId: '1:821231678050:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '821231678050',
    projectId: 'carpool-app-5abb3',
    authDomain: 'carpool-app-5abb3.firebaseapp.com',
    storageBucket: 'carpool-app-5abb3.firebasestorage.app',
  );
}
